/**
 * Regenerates the AI Weekly landing page (public/ai-weekly/index.html) and
 * polishes every dashboard under public/ai-weekly/RAW/ to match the site's
 * editorial paper theme.
 *
 * Workflow:
 *   1. Scan public/ai-weekly/RAW/*.html for AI Intel Weekly Dashboards.
 *   2. Parse the timestamp from each filename
 *      (ai-intel-dashboard-YYYYMMDD-HHMMSS.html) plus light metadata from the
 *      HTML (title, "as of" date, source count, "top X of Y" candidates).
 *   3. Write a fully themed copy of each dashboard into public/ai-weekly/pages/
 *      named ai-weekly-digest-YYYYMMDD-HHMMSS.html (same timestamp suffix). The
 *      copy gets the editorial paper palette/fonts + a back-to-index site strip
 *      injected between marker comments. RAW/ is left pristine as the source.
 *   4. Rebuild index.html: a hero, a derived stats bar, and one card per
 *      dashboard sorted newest-first, linking into pages/.
 *
 * Usage:
 *   npx tsx scripts/build-ai-weekly-index.ts          # write changes
 *   npx tsx scripts/build-ai-weekly-index.ts --check   # fail if out of date
 *
 * Dashboard HTML is machine-generated by an external pipeline and is treated
 * as trusted local content. Only run this on your own files.
 */

import {
  readdirSync,
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { renderNavbarBlock } from "./lib/static-navbar.js";

const NAV_BLOCK = renderNavbarBlock("/ai-weekly/");

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const AI_WEEKLY = join(ROOT, "public", "ai-weekly");
const RAW_DIR = join(AI_WEEKLY, "RAW");
const PAGES_DIR = join(AI_WEEKLY, "pages");
const INDEX_FILE = join(AI_WEEKLY, "index.html");

const FILE_RE = /^ai-intel-dashboard-(\d{8})-(\d{6})\.html$/i;

interface Digest {
  /** Source filename in RAW/, e.g. ai-intel-dashboard-20260530-225115.html. */
  file: string;
  /** Themed output filename in pages/, e.g. ai-weekly-digest-20260530-225115.html. */
  pageFile: string;
  /** Sortable key: YYYYMMDDHHMMSS from the filename. */
  stamp: string;
  /** Display date "2026 · 05 · 30". */
  date: string;
  /** Display time "14:51 UTC" (from the dashboard, falls back to filename). */
  time: string;
  title: string;
  sources: number;
  topN: number | null;
  total: number | null;
}

function match1(html: string, re: RegExp): string | null {
  const m = html.match(re);
  return m ? m[1].trim() : null;
}

function parseDigest(file: string): Digest | null {
  const m = file.match(FILE_RE);
  if (!m) return null;
  const [, d, t] = m;
  const html = readFileSync(join(RAW_DIR, file), "utf8");

  const title =
    match1(html, /<title>([^<]*?)\s*(?:-|–|\u2013)?\s*\d{4}-\d{2}-\d{2}[^<]*<\/title>/i) ??
    match1(html, /<title>([^<]+)<\/title>/i) ??
    "AI Intelligence Weekly Digest";

  // Time of day: prefer the <span class="timestamp"> in the report header.
  const tsSpan = match1(html, /<span class="timestamp">([^<]+)<\/span>/i);
  let time = `${t.slice(0, 2)}:${t.slice(2, 4)} UTC`;
  if (tsSpan) {
    const tm = tsSpan.match(/(\d{2}:\d{2})\s*UTC/i);
    if (tm) time = `${tm[1]} UTC`;
  }

  const sourcesLine = match1(html, /Sources:\s*([^<]+)</i);
  const sources = sourcesLine
    ? sourcesLine.split(",").map((s) => s.trim()).filter(Boolean).length
    : 0;

  const showing = html.match(/Showing:\s*top\s*(\d+)\s*of\s*(\d+)/i);
  const topN = showing ? Number(showing[1]) : null;
  const total = showing ? Number(showing[2]) : null;

  return {
    file,
    pageFile: `ai-weekly-digest-${d}-${t}.html`,
    stamp: `${d}${t}`,
    date: `${d.slice(0, 4)} · ${d.slice(4, 6)} · ${d.slice(6, 8)}`,
    time,
    title,
    sources,
    topN,
    total,
  };
}

/* ------------------------------------------------------------------ *
 * Themed page generation — read RAW, inject theme, write to pages/     *
 * ------------------------------------------------------------------ */

const FONT_LINKS = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,900&family=Newsreader:opsz,wght@6..72,400;6..72,450;6..72,600&family=JetBrains+Mono:wght@400;600;700&display=swap" rel="stylesheet">`;

const THEME_OVERRIDE = `<style id="site-theme-override">
  /* Editorial paper theme — overrides the dashboard's default SaaS palette.
     Re-declares :root vars (later wins) and remaps fonts + accent surfaces. */
  :root{
    --bg:#f4f1ea; --panel:#fbf9f4; --panel-soft:#f3efe6; --text:#1b1a17;
    --muted:#6b6557; --line:#e1dccf; --line-strong:#d8d2c4; --head:#efe9db;
    --accent:#cc3b1d; --accent-soft:#f3ddd4;
    --shadow:0 16px 40px -18px rgba(27,26,23,.30);
  }
  body{font-family:"Newsreader",Georgia,serif !important;}
  h1{font-family:"Fraunces",serif !important;font-weight:600 !important;letter-spacing:-.015em !important;}
  .eyebrow,.timestamp,.meta li,th,label,button,select,.filter-count,
  .type-badge,.confidence,.score,.summary-teaser-label,.rank,.score-cell{
    font-family:"JetBrains Mono",monospace !important;
  }
  .eyebrow{letter-spacing:.22em !important;}
  .title-cell,.title-link{color:#1b1a17 !important;}
  .title-link{text-decoration-color:rgba(204,59,29,.32) !important;}
  .title-link:hover{color:var(--accent) !important;text-decoration-color:currentColor !important;}
  button{background:#1b1a17 !important;}
  button:disabled{background:#cdc6b6 !important;}
  tbody tr:hover{background:#f3ddd4 !important;}
  .summary-teaser{background:#f3efe6 !important;border-left-color:var(--accent) !important;color:#4a463d !important;}
  /* badge + score + confidence retinted to slate / amber / vermillion lanes */
  .type-paper{background:#dde7e6 !important;color:#2f5d62 !important;}
  .type-page{background:#ece7db !important;color:#4a463d !important;}
  .type-video{background:#f3ddd4 !important;color:#cc3b1d !important;}
  .type-post{background:#f4e9cf !important;color:#9a6a00 !important;}
  .score{background:#f4e9cf !important;color:#9a6a00 !important;}
  .confidence-high{background:#dde7e6 !important;color:#2f5d62 !important;}
  .confidence-medium{background:#f4e9cf !important;color:#9a6a00 !important;}
  .confidence-low,.confidence-unknown{background:#f3ddd4 !important;color:#cc3b1d !important;}
  /* site strip */
  .site-strip{display:flex;align-items:center;justify-content:space-between;gap:16px;
    flex-wrap:wrap;padding:13px clamp(16px,2vw,36px);background:var(--panel);
    border-bottom:1px solid var(--line-strong);
    font-family:"JetBrains Mono",monospace;font-size:11.5px;letter-spacing:.14em;
    text-transform:uppercase;font-weight:600;}
  .site-strip a{color:var(--accent);text-decoration:none;font-weight:700;}
  .site-strip a:hover{text-decoration:underline;}
  .site-strip .brand{color:var(--muted);letter-spacing:.18em;}
  .site-strip .brand b{color:var(--text);font-weight:700;}
</style>`;

const SITE_STRIP = `<nav class="site-strip" aria-label="Site">
  <a href="../index.html">&larr; AI Weekly index</a>
  <span class="brand">PM <b>Studio</b> · AI Intel</span>
  <a href="/">PM Studio home</a>
</nav>`;

/** Build the themed page HTML for a digest from its pristine RAW source. */
function renderPage(d: Digest): string {
  let html = readFileSync(join(RAW_DIR, d.file), "utf8");

  // 1) Theme override + fonts before </head>.
  const headBody = `${FONT_LINKS}\n${THEME_OVERRIDE}`;
  html = html.replace(
    /<\/head>/i,
    `<!-- SITE-THEME:START -->\n${headBody}\n<!-- SITE-THEME:END -->\n</head>`,
  );

  // 2) Global navbar + site strip right after <body>.
  html = html.replace(
    /<body[^>]*>/i,
    (m) =>
      `${m}\n${NAV_BLOCK}\n<!-- SITE-STRIP:START -->\n${SITE_STRIP}\n<!-- SITE-STRIP:END -->`,
  );

  return html;
}

/* ------------------------------------------------------------------ *
 * Index page generation                                               *
 * ------------------------------------------------------------------ */

const LANES = ["agent", "applied", "advanced"] as const;

function renderCard(d: Digest, issue: number, position: number): string {
  const lane = LANES[position % LANES.length];
  const range =
    d.topN != null && d.total != null
      ? `${d.topN} of ${d.total} candidates`
      : "ranked digest";
  return `    <a class="issue cat-${lane}" href="pages/${d.pageFile}">
      <div class="i-meta">
        <span>Issue ${String(issue).padStart(2, "0")}</span><span class="dot"></span>
        <span class="date">${d.date}</span><span class="dot"></span>
        <span>${d.time}</span>
      </div>
      <h3>${d.title}</h3>
      <div class="i-stats">
        <span class="is"><b>${d.topN ?? "—"}</b> ranked</span>
        <span class="is"><b>${d.sources || "—"}</b> sources</span>
        <span class="is"><b>${d.total ?? "—"}</b> candidates</span>
      </div>
      <span class="open">Open digest · ${range} <span class="arw">→</span></span>
    </a>`;
}

function buildIndex(digests: Digest[]): string {
  const latest = digests[0];
  const totalSources = latest?.sources ?? 0;
  const latestTopN = latest?.topN ?? 0;
  const cards = digests
    .map((d, i) => renderCard(d, digests.length - i, i))
    .join("\n");

  const empty = `    <div class="empty-slot">
      <span class="es-k">Next issue</span>
      <span class="es-t">Drop a new dashboard into <code>RAW/</code></span>
      Name it <code>ai-intel-dashboard-YYYYMMDD-HHMMSS.html</code>, then run <code>npm run build:ai-weekly</code>. It sorts to the top automatically.
    </div>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<base href="/ai-weekly/">
<title>AI Weekly</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,900&family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,450;1,6..72,400&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>
:root{
  --paper:#f4f1ea; --ink:#1b1a17; --ink-soft:#4a463d; --rule:#d8d2c4;
  --accent:#cc3b1d; --accent-soft:#f3ddd4;
  --slate:#2f5d62; --slate-soft:#dde7e6;
  --amber:#9a6a00; --amber-soft:#f4e9cf;
  --card:#fbf9f4;
}
*,*::before,*::after{box-sizing:border-box;}
html{scroll-behavior:smooth;}
body{margin:0;background:var(--paper);color:var(--ink);font-family:"Newsreader",Georgia,serif;font-size:18px;line-height:1.6;-webkit-font-smoothing:antialiased;}
.wrap{max-width:1040px;margin:0 auto;padding:0 28px 120px;}
code,.mono{font-family:"JetBrains Mono",monospace;font-size:.82em;background:#ece7db;padding:.08em .38em;border-radius:4px;color:#3a382f;}
a{color:inherit;}

.hero{padding:90px 0 24px;position:relative;}
.kicker{font-family:"JetBrains Mono",monospace;font-size:12px;letter-spacing:.32em;text-transform:uppercase;color:var(--accent);font-weight:600;margin-bottom:16px;}
.hero h1{font-family:"Fraunces",serif;font-weight:600;font-size:clamp(46px,7vw,80px);line-height:1.0;margin:0 0 22px;letter-spacing:-.02em;max-width:880px;}
.hero h1 em{font-style:italic;color:var(--accent);}
.hero .dek{font-family:"Newsreader",Georgia,serif;font-style:italic;font-size:23px;color:var(--ink-soft);line-height:1.5;margin:0 0 22px;max-width:760px;}
.spark{position:absolute;top:96px;right:0;width:120px;height:120px;opacity:.85;}
@media(max-width:880px){.spark{display:none;}}

.stats{display:flex;flex-wrap:wrap;margin:38px 0 6px;border:1px solid var(--rule);border-radius:11px;overflow:hidden;background:var(--card);}
.stats .s{flex:1 1 140px;padding:18px 22px;border-right:1px solid var(--rule);}
.stats .s:last-child{border-right:none;}
.stats .s .v{font-family:"Fraunces",serif;font-weight:900;font-size:30px;color:var(--accent);line-height:1;}
.stats .s .l{font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:var(--ink-soft);margin-top:7px;}

.sec-label{font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--ink-soft);margin:54px 0 8px;font-weight:600;}

.issues{margin:14px 0 0;display:grid;gap:16px;}
.issue{display:block;text-decoration:none;color:inherit;background:var(--card);border:1px solid var(--rule);border-left:5px solid var(--c,var(--slate));border-radius:13px;padding:26px 30px 24px;transition:transform .16s ease,box-shadow .16s ease;}
.issue:hover{transform:translateY(-3px);box-shadow:0 14px 34px -14px rgba(27,26,23,.26);}
.issue.cat-agent{--c:var(--slate);}
.issue.cat-applied{--c:var(--amber);}
.issue.cat-advanced{--c:var(--accent);}
.i-meta{display:flex;align-items:center;gap:11px;flex-wrap:wrap;margin-bottom:11px;font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--c);font-weight:600;}
.i-meta .dot{width:5px;height:5px;border-radius:50%;background:var(--c);opacity:.55;}
.i-meta .date{color:var(--ink-soft);}
.issue h3{font-family:"Fraunces",serif;font-weight:600;font-size:27px;line-height:1.12;margin:0 0 14px;letter-spacing:-.012em;}
.i-stats{display:flex;gap:26px;flex-wrap:wrap;margin:0 0 16px;padding:13px 0 0;border-top:1px dashed var(--rule);}
.i-stats .is{font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--ink-soft);}
.i-stats .is b{font-family:"Fraunces",serif;font-weight:600;font-size:19px;color:var(--c);letter-spacing:0;margin-right:5px;}
.issue .open{font-family:"JetBrains Mono",monospace;font-size:12px;font-weight:600;color:var(--c);letter-spacing:.05em;}
.issue .arw{display:inline-block;margin-left:4px;transition:transform .15s;}
.issue:hover .arw{transform:translateX(4px);}

.empty-slot{border:1.5px dashed var(--rule);border-radius:13px;padding:30px 32px;color:var(--ink-soft);font-style:italic;text-align:center;background:transparent;}
.empty-slot .es-k{font-family:"JetBrains Mono",monospace;font-style:normal;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--ink-soft);display:block;margin-bottom:8px;font-weight:600;opacity:.8;}
.empty-slot .es-t{font-family:"Fraunces",serif;font-style:normal;font-size:21px;color:var(--ink);font-weight:600;display:block;margin-bottom:6px;}

.howto{background:var(--card);border:1px solid var(--rule);border-radius:11px;padding:24px 28px;margin:36px 0 0;}
.howto h4{font-family:"Fraunces",serif;font-weight:600;font-size:20px;margin:0 0 10px;}
.howto ul{margin:0;padding-left:0;list-style:none;}
.howto li{padding:6px 0 6px 22px;position:relative;font-size:16px;line-height:1.5;color:var(--ink-soft);}
.howto li::before{content:"▸";position:absolute;left:0;color:var(--accent);font-size:14px;top:8px;}
.howto code{font-size:.78em;}

footer{margin-top:80px;padding-top:28px;border-top:1px solid var(--rule);font-family:"JetBrains Mono",monospace;font-size:11.5px;color:var(--ink-soft);line-height:1.6;}

@media(max-width:760px){
  .hero{padding:60px 0 16px;}
  .issue{padding:22px 20px;}
  .issue h3{font-size:23px;}
}
</style>
</head>
<body>
${NAV_BLOCK}
<div class="wrap">

<header class="hero">
  <svg class="spark" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M50 8 L57 42 L92 50 L57 58 L50 92 L43 58 L8 50 L43 42 Z" fill="#cc3b1d" opacity=".85"/>
    <circle cx="50" cy="50" r="6" fill="#2f5d62"/>
  </svg>
  <div class="kicker">Personal Intelligence Brief · AI</div>
  <h1>AI <em>Weekly</em></h1>
  <p class="dek">A running shelf of AI Intelligence digests — each issue ranks the week's most important papers, releases, and videos across dozens of sources. Newest issue sits up top; the archive runs below.</p>
</header>

<!-- AUTO-INDEX:STATS:START -->
<div class="stats">
  <div class="s"><div class="v">${digests.length}</div><div class="l">Issues</div></div>
  <div class="s"><div class="v">${latest?.date.split(" · ").slice(1).join("/") ?? "—"}</div><div class="l">Latest Issue</div></div>
  <div class="s"><div class="v">${totalSources || "—"}</div><div class="l">Sources Tracked</div></div>
  <div class="s"><div class="v">${latestTopN || "—"}</div><div class="l">Ranked This Week</div></div>
</div>
<!-- AUTO-INDEX:STATS:END -->

<div class="sec-label">Every issue — newest first, click to open</div>

<!-- AUTO-INDEX:ISSUES:START -->
<div class="issues">
${cards}
${empty}
</div>
<!-- AUTO-INDEX:ISSUES:END -->

<div class="sec-label">How this index works</div>
<div class="howto">
  <h4>Conventions</h4>
  <ul>
    <li><b>One file per issue</b> — source dashboards live (pristine) in <code>RAW/</code> named <code>ai-intel-dashboard-YYYYMMDD-HHMMSS.html</code>. The timestamp sorts freshness.</li>
    <li><b>This page is generated</b> — run <code>npm run build:ai-weekly</code> after adding a dashboard. It rebuilds the cards and stats, and writes a site-themed copy of the dashboard into <code>pages/</code>.</li>
    <li><b>Self-contained</b> — each dashboard bundles its own data, filters, and sort. The index only links to the themed <code>pages/</code> copies.</li>
    <li><b>Theming is automatic</b> — the generator copies each <code>RAW/</code> dashboard into <code>pages/</code> as <code>ai-weekly-digest-YYYYMMDD-HHMMSS.html</code> with the editorial palette and a back-to-index strip applied. <code>RAW/</code> stays untouched.</li>
  </ul>
</div>

<footer>
  AI WEEKLY · PERSONAL INTELLIGENCE BRIEF · 2026<br>
  EACH ISSUE IS A SNAPSHOT — VERIFY FAST-MOVING SPECIFICS AGAINST CURRENT SOURCES BEFORE RELYING ON THEM.
</footer>

</div>
</body>
</html>
`;
}

/* ------------------------------------------------------------------ */

function main(): void {
  const check = process.argv.includes("--check");
  if (!existsSync(RAW_DIR)) {
    throw new Error(`RAW directory not found: ${RAW_DIR}`);
  }

  const digests = readdirSync(RAW_DIR)
    .map(parseDigest)
    .filter((d): d is Digest => d !== null)
    .sort((a, b) => (a.stamp < b.stamp ? 1 : -1)); // newest first

  if (digests.length === 0) {
    throw new Error(
      `No dashboards matching ai-intel-dashboard-YYYYMMDD-HHMMSS.html in ${RAW_DIR}`,
    );
  }

  const html = buildIndex(digests);
  const indexCurrent = existsSync(INDEX_FILE) ? readFileSync(INDEX_FILE, "utf8") : "";

  // Themed pages: compare desired vs on-disk.
  const pages = digests.map((d) => {
    const path = join(PAGES_DIR, d.pageFile);
    const desired = renderPage(d);
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    return { d, path, desired, stale: desired !== current };
  });
  const stalePages = pages.filter((p) => p.stale);

  if (check) {
    const problems: string[] = [];
    if (html !== indexCurrent) problems.push("ai-weekly/index.html");
    for (const p of stalePages) problems.push(`pages/${p.d.pageFile}`);
    if (problems.length > 0) {
      console.error(
        `AI Weekly out of date (${problems.join(", ")}). Run: npm run build:ai-weekly`,
      );
      process.exit(1);
    }
    console.log("AI Weekly index and pages are up to date.");
    return;
  }

  if (!existsSync(PAGES_DIR)) mkdirSync(PAGES_DIR, { recursive: true });
  for (const p of stalePages) {
    writeFileSync(p.path, p.desired, "utf8");
  }
  if (html !== indexCurrent) {
    writeFileSync(INDEX_FILE, html, "utf8");
  }
  console.log(
    `AI Weekly: ${digests.length} issue(s); index ${
      html !== indexCurrent ? "written" : "unchanged"
    }; wrote ${stalePages.length} themed page(s)` +
      (stalePages.length
        ? `: ${stalePages.map((p) => p.d.pageFile).join(", ")}`
        : "."),
  );
}

main();
